base_config: singing/svs/config/base_rms.yaml

lr: 0.001
decay_steps: 50000
gaussian_start: false
dilation_cycle_length: 4  # *
predictor_layers: 5
diff_loss_type: l1
diff_decoder_type: 'wavenet'
schedule_type: 'linear'
residual_layers: 20
residual_channels: 256
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
weight_decay: 0
keep_bins: 80
timesteps: 100
K_step: 100
max_beta: 0.06

spec_min: [-6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0]

spec_max: [0.03640973940491676, 0.039425432682037354, 0.29524752497673035, 0.45784831047058105, 0.48333120346069336, 0.5335848927497864, 0.6071611046791077, 0.5474293828010559, 0.6076506972312927, 0.5390501022338867, 0.5743886232376099, 0.485751211643219, 0.4248744249343872, 0.4843744933605194, 0.43331536650657654, 0.5356124639511108, 0.4875929355621338, 0.48614853620529175, 0.44228559732437134, 0.5027499198913574, 0.6554337739944458, 0.3469322919845581, 0.33981558680534363, 0.37933868169784546, 0.34751009941101074, 0.22094282507896423, 0.252963662147522, 0.18274202942848206, 0.1976650059223175, 0.1770155429840088, 0.18206502497196198, 0.1002601608633995, 0.18640224635601044, 0.27240633964538574, 0.04153885692358017, -0.010289354249835014, -0.012929759919643402, 0.035185474902391434, 0.18124309182167053, -0.14512233436107635, -0.1778590828180313, -0.20491982996463776, -0.30119436979293823, -0.1735714226961136, -0.1039585992693901, -0.177497997879982, -0.28803232312202454, -0.24049188196659088, -0.4682924747467041, -0.5791841745376587, -0.5170156955718994, -0.6380605697631836, -0.7147259712219238, -0.6607836484909058, -0.7288452982902527, -0.6338580250740051, -0.7092624306678772, -0.8101216554641724, -0.7633087038993835, -0.8251329660415649, -0.6936700940132141, -0.5180960297584534, -0.7972619533538818, -0.807314932346344, -0.7151175737380981, -0.7785399556159973, -0.8709449768066406, -0.8360402584075928, -0.8253681659698486, -0.9778416156768799, -1.12929368019104, -1.3274869918823242, -1.3071579933166504, -1.5234452486038208, -1.6191706657409668, -1.708594799041748, -1.8246771097183228, -1.9193823337554932, -2.1361801624298096, -2.3829283714294434]
